Repository GymHubCommunity/GymHub-BE, pull requests merged in 2024-03, with the labels that each got.

#175 [#174] "대기 상태인 팔로우 요청" 무한스크롤 조회
  src/main/java/com/example/temp/follow/application/FollowService.java
  src/main/java/com/example/temp/follow/domain/FollowRepository.java
  src/main/java/com/example/temp/follow/presentation/FollowController.java
  src/test/java/com/example/temp/follow/application/FollowServiceTest.java
  src/test/java/com/example/temp/follow/domain/FollowRepositoryTest.java
Labels: 💪🏻 feat

#179 [#178] feat: 회원이 계정 Privacy 정책을 변경할 때, 팔로우 전략을 함께 바꾸도록 구현
  src/main/java/com/example/temp/member/domain/Member.java
  src/main/java/com/example/temp/member/domain/PrivacyPolicy.java
  src/test/java/com/example/temp/member/domain/MemberTest.java
Labels: 🐞 BugFix

#181 [#180] memberId로 게시글 리스트 조회 api 추가
  src/main/java/com/example/temp/post/application/PostService.java
  src/main/java/com/example/temp/post/domain/PostRepository.java
  src/main/java/com/example/temp/post/presentation/MemberPostController.java
  src/test/java/com/example/temp/post/application/PostServiceTest.java
  src/test/java/com/example/temp/post/domain/PostRepositoryTest.java
Labels: 💪🏻 feat

#177 [#176] 500 서버 에러 발생 시 알림 보내주기
  build.gradle
  src/main/java/com/example/temp/common/config/DiscordConfig.java
  src/main/java/com/example/temp/common/exception/ExceptionInfo.java
  src/main/java/com/example/temp/common/exception/ExceptionSenderNotWorkingException.java
  src/main/java/com/example/temp/common/exception/GlobalExceptionHandler.java
  src/main/java/com/example/temp/common/infrastructure/exceptionsender/DiscordExceptionSender.java
  src/main/java/com/example/temp/common/infrastructure/exceptionsender/ExceptionSender.java
  src/test/java/com/example/temp/TestConfig.java
  src/test/java/com/example/temp/common/exception/ExceptionInfoTest.java
  src/test/java/com/example/temp/common/infrastructure/exceptionsender/DiscordDiscordBodyValueTest.java
  src/test/java/com/example/temp/common/infrastructure/exceptionsender/DiscordExceptionSenderTest.java
  src/test/java/com/example/temp/exception/GlobalExceptionHandlerUnitTest.java
Labels: 💪🏻 feat, ⚙ Setting

#183 [#182] GET /machines/search 요청 시 WHOLE 카테고리 함께 나오도록 변경
  src/main/java/com/example/temp/machine/application/MachineService.java
  src/main/java/com/example/temp/machine/domain/BodyPart.java
  src/test/java/com/example/temp/machine/application/MachineServiceTest.java
Labels: 🔨 refactor

#185 [#184] Jwt 토큰 관련 예외 처리
  src/main/java/com/example/temp/common/exception/GlobalExceptionHandler.java
  src/test/java/com/example/temp/exception/GlobalExceptionHandlerUnitTest.java
Labels: 💪🏻 feat

#187 [#186] refactor: S3 CORS url 추가
  docker-compose.yml
Labels: 🔨 refactor
