Repository GymHubCommunity/GymHub-BE, pull requests merged in 2024-02, with the labels that each got.

#10 [GymHubCommunity#5] chore: Dockerfile 생성
  Dockerfile
Labels: 🌏 Deploy, ⚙ Setting

#15 [#14] application.yml gitignore 처리
  .gitignore
  Dockerfile
  build.gradle
  src/main/java/com/example/temp/auth/dto/request/OAuthLoginRequest.java
  src/main/java/com/example/temp/auth/dto/response/AccessToken.java
  src/main/java/com/example/temp/auth/dto/response/LoginInfoResponse.java
  src/main/java/com/example/temp/auth/presentation/AuthController.java
  src/main/java/com/example/temp/common/config/ScanningPropertiesConfiguration.java
  src/main/java/com/example/temp/common/config/WebClientConfiguration.java
  src/main/java/com/example/temp/member/domain/Member.java
  src/main/java/com/example/temp/member/domain/MemberRepository.java
  src/main/java/com/example/temp/oauth/OAuthProvider.java
  src/main/java/com/example/temp/oauth/OAuthProviderResolver.java
  src/main/java/com/example/temp/oauth/OAuthProviderType.java
  src/main/java/com/example/temp/oauth/OAuthResponse.java
  src/main/java/com/example/temp/oauth/OAuthUserInfo.java
  src/main/java/com/example/temp/oauth/application/OAuthService.java
  src/main/java/com/example/temp/oauth/domain/OAuthInfo.java
  src/main/java/com/example/temp/oauth/domain/OAuthInfoRepository.java
  src/main/java/com/example/temp/oauth/impl/google/GoogleOAuthClient.java
  src/main/java/com/example/temp/oauth/impl/google/GoogleOAuthProperties.java
  src/main/java/com/example/temp/oauth/impl/google/GoogleOAuthProvider.java
  src/main/java/com/example/temp/oauth/impl/google/GoogleToken.java
  src/main/java/com/example/temp/oauth/impl/google/GoogleUserInfo.java
  src/main/resources/application.yml
  src/test/java/com/example/temp/auth/application/OAuthServiceUnitTest.java
  src/test/java/com/example/temp/member/domain/MemberTest.java
  src/test/java/com/example/temp/oauth/OAuthProviderResolverUnitTest.java
  src/test/java/com/example/temp/oauth/OAuthProviderTypeTest.java
  src/test/java/com/example/temp/oauth/OAuthResponseTest.java
  src/test/java/com/example/temp/oauth/domain/OAuthInfoRepositoryTest.java
  src/test/java/com/example/temp/oauth/domain/OAuthInfoTest.java
  src/test/java/com/example/temp/oauth/impl/google/GoogleOAuthProviderTest.java
  src/test/java/com/example/temp/oauth/impl/google/GoogleTokenTest.java
Labels: ⚙ Setting

#17 [#14] application.yml gitignore 처리
  .gitignore
  src/main/resources/application.yml
Labels: ⚙ Setting

#8 [#6] 랜덤 닉네임 생성기 구현
  build.gradle
  src/main/java/com/example/temp/auth/dto/response/LoginInfoResponse.java
  src/main/java/com/example/temp/common/config/RetryConfig.java
  src/main/java/com/example/temp/member/application/MemberService.java
  src/main/java/com/example/temp/member/domain/Member.java
  src/main/java/com/example/temp/member/domain/MemberRepository.java
  src/main/java/com/example/temp/member/exception/NicknameDuplicatedException.java
  src/main/java/com/example/temp/member/infrastructure/nickname/FakerNicknameGenerator.java
  src/main/java/com/example/temp/member/infrastructure/nickname/NicknameGenerator.java
  src/main/java/com/example/temp/oauth/OAuthResponse.java
  src/main/java/com/example/temp/oauth/application/OAuthService.java
  src/test/java/com/example/temp/auth/application/OAuthServiceUnitTest.java
  src/test/java/com/example/temp/auth/dto/response/LoginInfoResponseTest.java
  src/test/java/com/example/temp/member/application/MemberServiceTest.java
  src/test/java/com/example/temp/member/domain/MemberRepositoryTest.java
  src/test/java/com/example/temp/member/domain/MemberTest.java
  src/test/java/com/example/temp/member/infrastructure/nickname/FakerNicknameGeneratorTest.java
  src/test/java/com/example/temp/oauth/OAuthResponseTest.java
  src/test/java/com/example/temp/oauth/domain/OAuthInfoRepositoryTest.java
Labels: 💪🏻 feat

#22 [#21] 예외 공통 처리 기능 구현
  src/main/java/com/example/temp/exception/ApiException.java
  src/main/java/com/example/temp/exception/ErrorCode.java
  src/main/java/com/example/temp/exception/ErrorResponse.java
  src/main/java/com/example/temp/exception/GlobalExceptionHandler.java
  src/test/java/com/example/temp/exception/GlobalExceptionHandlerUnitTest.java
Labels: 💪🏻 feat, ⚙ Setting

#25 [#23] Kakao OAuth2 로그인 구현
  src/main/java/com/example/temp/common/config/WebClientConfiguration.java
  src/main/java/com/example/temp/oauth/impl/google/GoogleOAuthClient.java
  src/main/java/com/example/temp/oauth/impl/kakao/KakaoOAuthClient.java
  src/main/java/com/example/temp/oauth/impl/kakao/KakaoOAuthProperties.java
  src/main/java/com/example/temp/oauth/impl/kakao/KakaoOAuthProvider.java
  src/main/java/com/example/temp/oauth/impl/kakao/KakaoToken.java
  src/main/java/com/example/temp/oauth/impl/kakao/KakaoUserInfo.java
  src/test/java/com/example/temp/oauth/impl/kakao/KakaoOAuthProviderTest.java
  src/test/java/com/example/temp/oauth/impl/kakao/KakaoTokenTest.java
Labels: 💪🏻 feat

#27 [#9] CORS 해제
  src/main/java/com/example/temp/common/config/WebConfig.java
  src/main/java/com/example/temp/common/properties/CorsProperties.java
Labels: ⚙ Setting

#29 [#28] Swagger 세팅
  build.gradle
  src/main/java/com/example/temp/common/config/SwaggerConfig.java
Labels: ⚙ Setting

#31 Feat/#30 BaseTimeEntity 추가
  src/main/java/com/example/temp/common/config/JpaAuditingConfig.java
  src/main/java/com/example/temp/common/entity/BaseTimeEntity.java
Labels: 💪🏻 feat

#11 [#4] Access Token, Refresh Token 생성
  build.gradle
  src/main/java/com/example/temp/auth/dto/response/LoginInfoResponse.java
  src/main/java/com/example/temp/auth/dto/response/LoginMemberResponse.java
  src/main/java/com/example/temp/auth/dto/response/LoginResponse.java
  src/main/java/com/example/temp/auth/dto/response/TokenInfo.java
  src/main/java/com/example/temp/auth/exception/TokenInvalidException.java
  src/main/java/com/example/temp/auth/infrastructure/JwtProperties.java
  src/main/java/com/example/temp/auth/infrastructure/JwtTokenManager.java
  src/main/java/com/example/temp/auth/infrastructure/TokenManager.java
  src/main/java/com/example/temp/auth/presentation/AuthController.java
  src/main/java/com/example/temp/auth/presentation/RefreshCookieProperties.java
  src/main/java/com/example/temp/common/config/ClockConfig.java
  src/main/java/com/example/temp/oauth/application/OAuthService.java
  src/test/java/com/example/temp/auth/application/OAuthServiceUnitTest.java
  src/test/java/com/example/temp/auth/dto/response/LoginMemberResponseTest.java
  src/test/java/com/example/temp/auth/dto/response/TokenInfoTest.java
  src/test/java/com/example/temp/auth/infrastructure/JwtTokenManagerTest.java
Labels: 💪🏻 feat

#33 [#32] OAuth 로그인이 가능한 URL 제공
  src/main/java/com/example/temp/auth/dto/response/AuthorizedUrl.java
  src/main/java/com/example/temp/auth/presentation/AuthController.java
  src/main/java/com/example/temp/oauth/OAuthProvider.java
  src/main/java/com/example/temp/oauth/OAuthProviderResolver.java
  src/main/java/com/example/temp/oauth/application/OAuthService.java
  src/main/java/com/example/temp/oauth/impl/google/GoogleOAuthProperties.java
  src/main/java/com/example/temp/oauth/impl/google/GoogleOAuthProvider.java
  src/main/java/com/example/temp/oauth/impl/kakao/KakaoOAuthProperties.java
  src/main/java/com/example/temp/oauth/impl/kakao/KakaoOAuthProvider.java
  src/test/java/com/example/temp/oauth/OAuthProviderResolverUnitTest.java
  src/test/java/com/example/temp/oauth/impl/google/GoogleOAuthProviderTest.java
  src/test/java/com/example/temp/oauth/impl/kakao/KakaoOAuthProviderTest.java
Labels: 💪🏻 feat

#35 [#34] SonarCloud와 Jacoco 연동
  .github/workflows/build.yml
  build.gradle
Labels: ⚙ Setting

#40 [#37] 사용자 인증, 인가
  src/main/java/com/example/temp/auth/infrastructure/JwtTokenManager.java
  src/main/java/com/example/temp/auth/infrastructure/TokenParser.java
  src/main/java/com/example/temp/auth/presentation/AuthController.java
  src/main/java/com/example/temp/common/config/WebConfig.java
  src/main/java/com/example/temp/common/interceptor/AuthenticationInterceptor.java
  src/test/java/com/example/temp/auth/infrastructure/JwtTokenManagerTest.java
  src/test/java/com/example/temp/common/interceptor/AuthenticationInterceptorTest.java
Labels: 💪🏻 feat

#45 [#41] 로그인 어노테이션 구현
  src/main/java/com/example/temp/auth/dto/MemberInfo.java
  src/main/java/com/example/temp/auth/infrastructure/JwtTokenManager.java
  src/main/java/com/example/temp/auth/infrastructure/Login.java
  src/main/java/com/example/temp/auth/infrastructure/LoginMemberArgumentResolver.java
  src/main/java/com/example/temp/auth/infrastructure/TokenParser.java
  src/main/java/com/example/temp/common/config/WebConfig.java
  src/main/java/com/example/temp/common/interceptor/AuthenticationInterceptor.java
  src/test/java/com/example/temp/auth/infrastructure/JwtTokenManagerTest.java
  src/test/java/com/example/temp/auth/infrastructure/LoginMemberArgumentResolverTest.java
  src/test/java/com/example/temp/common/interceptor/AuthenticationInterceptorTest.java
Labels: 💪🏻 feat

#47 [#46] 로그인 관련 클래스 패키지 이동
  src/main/java/com/example/temp/auth/dto/MemberInfo.java
  src/main/java/com/example/temp/auth/infrastructure/JwtTokenManager.java
  src/main/java/com/example/temp/auth/infrastructure/TokenParser.java
  src/main/java/com/example/temp/common/annotation/Login.java
  src/main/java/com/example/temp/common/config/WebConfig.java
  src/main/java/com/example/temp/common/dto/UserContext.java
  src/main/java/com/example/temp/common/interceptor/AuthenticationInterceptor.java
  src/main/java/com/example/temp/common/resolver/LoginUserArgumentResolver.java
  src/test/java/com/example/temp/auth/dto/response/UserContextTest.java
  src/test/java/com/example/temp/auth/infrastructure/JwtTokenManagerTest.java
  src/test/java/com/example/temp/auth/infrastructure/LoginUserArgumentResolverTest.java
  src/test/java/com/example/temp/common/interceptor/AuthenticationInterceptorTest.java
Labels: 🔨 refactor

#48 [#44] 회원 계정 Privacy 정책 설정
  src/main/java/com/example/temp/auth/dto/MemberInfo.java
  src/main/java/com/example/temp/common/config/WebConfig.java
  src/main/java/com/example/temp/common/convertor/StringToPrivacyPolicyConverter.java
  src/main/java/com/example/temp/common/dto/UserContext.java
  src/main/java/com/example/temp/common/exception/ApiException.java
  src/main/java/com/example/temp/common/exception/ErrorCode.java
  src/main/java/com/example/temp/common/exception/ErrorResponse.java
  src/main/java/com/example/temp/common/exception/GlobalExceptionHandler.java
  src/main/java/com/example/temp/follow/application/FollowService.java
  src/main/java/com/example/temp/follow/domain/Follow.java
  src/main/java/com/example/temp/follow/domain/FollowRepository.java
  src/main/java/com/example/temp/follow/presentation/FollowController.java
  src/main/java/com/example/temp/member/application/MemberService.java
  src/main/java/com/example/temp/member/domain/Member.java
  src/main/java/com/example/temp/member/domain/PrivacyPolicy.java
  src/main/java/com/example/temp/member/infrastructure/nickname/Nickname.java
  src/main/java/com/example/temp/member/presentation/MemberController.java
  src/test/java/com/example/temp/auth/dto/response/UserContextTest.java
  src/test/java/com/example/temp/common/convertor/StringToPrivacyPolicyConverterTest.java
  src/test/java/com/example/temp/exception/GlobalExceptionHandlerUnitTest.java
  src/test/java/com/example/temp/follow/application/FollowServiceTest.java
  src/test/java/com/example/temp/follow/domain/FollowRepositoryTest.java
  src/test/java/com/example/temp/follow/domain/FollowTest.java
  src/test/java/com/example/temp/member/application/MemberServiceTest.java
  src/test/java/com/example/temp/member/domain/MemberRepositoryTest.java
  src/test/java/com/example/temp/member/domain/MemberTest.java
  src/test/java/com/example/temp/member/infrastructure/nickname/NicknameTest.java
  src/test/java/com/example/temp/oauth/OAuthResponseTest.java
Labels: 💪🏻 feat

#53 [#39] 팔로우 중인 유저들의 게시글 목록 조회
  src/main/java/com/example/temp/common/exception/ErrorCode.java
  src/main/java/com/example/temp/post/application/PostService.java
  src/main/java/com/example/temp/post/domain/Content.java
  src/main/java/com/example/temp/post/domain/Post.java
  src/main/java/com/example/temp/post/domain/PostImage.java
  src/main/java/com/example/temp/post/domain/PostRepository.java
  src/main/java/com/example/temp/post/dto/response/PagePostResponse.java
  src/main/java/com/example/temp/post/dto/response/PostElementResponse.java
  src/main/java/com/example/temp/post/dto/response/WriterInfo.java
  src/main/java/com/example/temp/post/presentation/PostController.java
  src/test/java/com/example/temp/post/application/PostServiceTest.java
  src/test/java/com/example/temp/post/domain/PostRepositoryTest.java
Labels: 💪🏻 feat

#55 [#43, #49] 회원 삭제, 닉네임 중복 검사
  src/main/java/com/example/temp/common/exception/ErrorCode.java
  src/main/java/com/example/temp/follow/application/FollowService.java
  src/main/java/com/example/temp/follow/domain/FollowRepository.java
  src/main/java/com/example/temp/member/application/MemberService.java
  src/main/java/com/example/temp/member/domain/Member.java
  src/main/java/com/example/temp/member/domain/MemberRepository.java
  src/main/java/com/example/temp/member/event/MemberDeletedEvent.java
  src/main/java/com/example/temp/member/presentation/MemberController.java
  src/test/java/com/example/temp/follow/application/FollowServiceTest.java
  src/test/java/com/example/temp/follow/domain/FollowRepositoryTest.java
  src/test/java/com/example/temp/member/application/MemberServiceTest.java
Labels: 💪🏻 feat

#60 [#57, #59] Swagger 설정, jacoco 테스트 대상 변경
  build.gradle
  src/main/java/com/example/temp/auth/dto/MemberInfo.java
  src/main/java/com/example/temp/common/annotation/Login.java
  src/main/java/com/example/temp/common/config/SwaggerConfig.java
  src/main/java/com/example/temp/member/domain/Member.java
  src/main/resources/data.sql
  src/test/java/com/example/temp/common/config/SwaggerConfigTest.java
  src/test/resources/application.yml
Labels: ⚙ Setting

#63 [#62] 테스트 커버리지 분석 대상에서 common/config, **/presentation 경로 제거하기
  build.gradle
Labels: ⚙ Setting

#61 [#56] Presigned URL 발급
  build.gradle
  src/main/java/com/example/temp/common/config/S3Config.java
  src/main/java/com/example/temp/common/entity/Extension.java
  src/main/java/com/example/temp/common/exception/ErrorCode.java
  src/main/java/com/example/temp/common/exception/GlobalExceptionHandler.java
  src/main/java/com/example/temp/common/properties/S3Properties.java
  src/main/java/com/example/temp/common/utils/random/DefaultRandomGenerator.java
  src/main/java/com/example/temp/common/utils/random/RandomGenerator.java
  src/main/java/com/example/temp/follow/domain/FollowRepository.java
  src/main/java/com/example/temp/image/application/ImageService.java
  src/main/java/com/example/temp/image/domain/Image.java
  src/main/java/com/example/temp/image/domain/ImageRepository.java
  src/main/java/com/example/temp/image/dto/request/PresignedUrlRequest.java
  src/main/java/com/example/temp/image/dto/response/PresignedUrlResponse.java
  src/main/java/com/example/temp/image/presentation/ImageController.java
  src/main/java/com/example/temp/member/domain/nickname/RandomNicknameGenerator.java
  src/main/java/com/example/temp/oauth/domain/OAuthInfoRepository.java
  src/test/java/com/example/temp/common/entity/ExtensionTest.java
  src/test/java/com/example/temp/common/utils/random/DefaultRandomGeneratorTest.java
  src/test/java/com/example/temp/image/application/ImageServiceTest.java
  src/test/java/com/example/temp/image/domain/ImageTest.java
  src/test/java/com/example/temp/image/dto/response/PresignedUrlResponseTest.java
  src/test/java/com/example/temp/member/domain/nickname/RandomNicknameGeneratorTest.java
  src/test/resources/application.yml
Labels: 💪🏻 feat

#65 [#64] refactor: 게시글 작성날짜 반환
  src/main/java/com/example/temp/post/dto/response/PostElementResponse.java
Labels: 🔨 refactor

#67 [#66] 누락된 작업 추가
  .gitignore
  lombok.config
  src/main/java/com/example/temp/member/application/MemberService.java
  src/main/java/com/example/temp/member/domain/MemberRepository.java
  src/main/resources/data.sql
  src/test/java/com/example/temp/member/domain/MemberRepositoryTest.java
Labels: 🐞 BugFix

#69 [#66] LocalStack을 실행하는 docker-compose.yml 생성
  .gitignore
  docker-compose.yml
Labels: ⚙ Setting

#71 [#54] 게시글 작성
  src/main/java/com/example/temp/common/exception/ErrorCode.java
  src/main/java/com/example/temp/image/domain/Image.java
  src/main/java/com/example/temp/image/domain/ImageRepository.java
  src/main/java/com/example/temp/post/application/PostService.java
  src/main/java/com/example/temp/post/domain/Content.java
  src/main/java/com/example/temp/post/domain/Post.java
  src/main/java/com/example/temp/post/domain/PostImage.java
  src/main/java/com/example/temp/post/dto/request/PostCreateRequest.java
  src/main/java/com/example/temp/post/dto/response/PostCreateResponse.java
  src/main/java/com/example/temp/post/dto/response/PostElementResponse.java
  src/main/java/com/example/temp/post/presentation/PostController.java
  src/test/java/com/example/temp/image/application/ImageServiceTest.java
  src/test/java/com/example/temp/image/domain/ImageTest.java
  src/test/java/com/example/temp/post/application/PostServiceTest.java
  src/test/java/com/example/temp/post/domain/PostRepositoryTest.java
  src/test/java/com/example/temp/post/domain/PostTest.java
Labels: 💪🏻 feat

#74 data.sql에서 members 초기화할 때 member_id 제거
  src/main/resources/data.sql
Labels: 🐞 BugFix

#80 [#79] CORS 문제 해결
  src/main/java/com/example/temp/common/interceptor/AuthenticationInterceptor.java
Labels: 🌏 Deploy

#82 [#81] HTTPS 연동
  .gitignore
Labels: 🌏 Deploy

#86 [#85] 개발 환경에서 Swagger 활성화
  src/main/java/com/example/temp/common/config/S3Config.java
  src/main/java/com/example/temp/common/config/SwaggerConfig.java
Labels: 🐞 BugFix, 🌏 Deploy

#88 [#87] HttpMessageNotReadableException 발생 시 클라이언트에게 메세지 보여주기
  src/main/java/com/example/temp/common/exception/GlobalExceptionHandler.java
Labels: 💪🏻 feat

#89 [#76] 운동기구 등록, 신체부위를 사용한 운동기구 목록 검색
  src/main/java/com/example/temp/admin/presentation/AdminController.java
  src/main/java/com/example/temp/common/exception/ErrorCode.java
  src/main/java/com/example/temp/machine/application/MachineService.java
  src/main/java/com/example/temp/machine/domain/BodyPart.java
  src/main/java/com/example/temp/machine/domain/Machine.java
  src/main/java/com/example/temp/machine/domain/MachineBodyPart.java
  src/main/java/com/example/temp/machine/domain/MachineRepository.java
  src/main/java/com/example/temp/machine/dto/request/MachineBulkCreateRequest.java
  src/main/java/com/example/temp/machine/dto/request/MachineCreateRequest.java
  src/main/java/com/example/temp/machine/dto/request/MachineSearchUsingBodyPartRequest.java
  src/main/java/com/example/temp/machine/dto/response/MachineCreateResponse.java
  src/main/java/com/example/temp/machine/dto/response/MachineInfo.java
  src/main/java/com/example/temp/machine/dto/response/MachineSearchUsingBodyPartResponse.java
  src/main/java/com/example/temp/machine/presentation/MachineController.java
  src/test/java/com/example/temp/machine/application/MachineServiceTest.java
  src/test/java/com/example/temp/machine/domain/MachineBodyPartTest.java
  src/test/java/com/example/temp/machine/domain/MachineRepositoryTest.java
  src/test/java/com/example/temp/machine/domain/MachineTest.java
  src/test/java/com/example/temp/machine/dto/request/MachineBulkCreateRequestTest.java
  src/test/java/com/example/temp/machine/dto/request/MachineCreateRequestTest.java
  src/test/java/com/example/temp/machine/dto/request/MachineSearchUsingBodyPartRequestTest.java
  src/test/java/com/example/temp/machine/dto/response/MachineInfoTest.java
  src/test/java/com/example/temp/machine/dto/response/MachineSearchUsingBodyPartResponseTest.java
  src/test/resources/application.yml
Labels: 💪🏻 feat

#92 [#91] refactor: 파일 저장 형식을 파일 이름에서 url로 변경
  src/main/java/com/example/temp/image/application/ImageService.java
  src/test/java/com/example/temp/image/application/ImageServiceTest.java
Labels: 🔨 refactor

#97 [#96] data.sql 초기 데이터 추가
  src/main/resources/data.sql
Labels: ⚙ Setting

#101 [#100] 쿠키 없을 떄 예외 처리
  src/main/java/com/example/temp/common/exception/GlobalExceptionHandler.java
Labels: 💪🏻 feat

#103 [#102] Dockerfile 수정
  Dockerfile
Labels: 🔨 refactor

#98 [#94] 팔로우, 팔로잉 목록 조회 무한스크롤로 변경
  src/main/java/com/example/temp/follow/application/FollowService.java
  src/main/java/com/example/temp/follow/domain/Follow.java
  src/main/java/com/example/temp/follow/domain/FollowRepository.java
  src/main/java/com/example/temp/follow/dto/response/FollowInfoResult.java
  src/main/java/com/example/temp/follow/presentation/FollowController.java
  src/test/java/com/example/temp/follow/application/FollowServiceTest.java
  src/test/java/com/example/temp/follow/domain/FollowRepositoryTest.java
  src/test/java/com/example/temp/follow/dto/response/FollowInfoResultTest.java
  src/test/java/com/example/temp/member/application/MemberServiceTest.java
Labels: 💪🏻 feat

#99 [#84] 게시글 상세보기
  src/main/java/com/example/temp/common/exception/ErrorCode.java
  src/main/java/com/example/temp/post/application/PostService.java
  src/main/java/com/example/temp/post/domain/Post.java
  src/main/java/com/example/temp/post/dto/response/PostDetailResponse.java
  src/main/java/com/example/temp/post/presentation/PostController.java
  src/test/java/com/example/temp/post/application/PostServiceTest.java
Labels: 💪🏻 feat

#108 [106] refactor: presignedUrl 쿼리파라미터 제외 전체 url 저장하도록 변경
  src/main/java/com/example/temp/image/application/ImageService.java
  src/test/java/com/example/temp/image/application/ImageServiceTest.java
Labels: 🔨 refactor

#113 [#112] 무한스크롤을 위해 Page -> Slice로 변경
  src/main/java/com/example/temp/post/application/PostService.java
  src/main/java/com/example/temp/post/domain/PostRepository.java
  src/main/java/com/example/temp/post/dto/response/SlicePostResponse.java
  src/main/java/com/example/temp/post/presentation/PostController.java
  src/test/java/com/example/temp/post/application/PostServiceTest.java
  src/test/java/com/example/temp/post/domain/PostRepositoryTest.java
Labels: 🔨 refactor

#114 [#110] 게시글 수정
  src/main/java/com/example/temp/common/exception/ErrorCode.java
  src/main/java/com/example/temp/image/domain/Image.java
  src/main/java/com/example/temp/image/domain/ImageRepository.java
  src/main/java/com/example/temp/post/application/PostService.java
  src/main/java/com/example/temp/post/domain/Post.java
  src/main/java/com/example/temp/post/domain/PostImage.java
  src/main/java/com/example/temp/post/dto/request/PostUpdateRequest.java
  src/main/java/com/example/temp/post/presentation/PostController.java
  src/test/java/com/example/temp/post/application/PostServiceTest.java
  src/test/java/com/example/temp/post/domain/PostRepositoryTest.java
Labels: 💪🏻 feat

#117 [#115] 게시글 삭제
  src/main/java/com/example/temp/hashtag/domain/Hashtag.java
  src/main/java/com/example/temp/post/application/PostService.java
  src/main/java/com/example/temp/post/domain/PostHashtagRepository.java
  src/main/java/com/example/temp/post/domain/PostImageRepository.java
  src/main/java/com/example/temp/post/domain/PostRepository.java
  src/main/java/com/example/temp/post/presentation/PostController.java
  src/test/java/com/example/temp/hashtag/domain/HashtagRepositoryTest.java
  src/test/java/com/example/temp/member/application/MemberServiceTest.java
  src/test/java/com/example/temp/post/application/PostServiceTest.java
  src/test/java/com/example/temp/post/domain/PostRepositoryTest.java
Labels: 💪🏻 feat

#120 [#119] 운동 기구 검색
  src/main/java/com/example/temp/admin/presentation/AdminController.java
  src/main/java/com/example/temp/machine/application/MachineService.java
  src/main/java/com/example/temp/machine/domain/BodyPart.java
  src/main/java/com/example/temp/machine/domain/MachineRepository.java
  src/main/java/com/example/temp/machine/dto/request/MachineCreateRequest.java
  src/main/java/com/example/temp/machine/dto/response/MachineInfo.java
  src/main/java/com/example/temp/machine/dto/response/MachineSearchAllResponse.java
  src/main/java/com/example/temp/machine/dto/response/MachineSearchUsingBodyCategoryResponse.java
  src/main/java/com/example/temp/machine/dto/response/MachineSearchUsingBodyPartResponse.java
  src/main/java/com/example/temp/machine/dto/response/MachineSummary.java
  src/main/java/com/example/temp/machine/presentation/MachineController.java
  src/test/java/com/example/temp/machine/application/MachineServiceTest.java
  src/test/java/com/example/temp/machine/domain/MachineBodyPartTest.java
  src/test/java/com/example/temp/machine/domain/MachineRepositoryTest.java
  src/test/java/com/example/temp/machine/dto/request/MachineSearchUsingBodyPartRequestTest.java
  src/test/java/com/example/temp/machine/dto/response/MachineInfoTest.java
  src/test/java/com/example/temp/machine/dto/response/MachineSearchUsingBodyPartResponseTest.java
Labels: 💪🏻 feat

#125 [#124] 게시글 리스트 리팩토링
  src/main/java/com/example/temp/post/application/PostService.java
  src/main/java/com/example/temp/post/presentation/PostController.java
  src/test/java/com/example/temp/post/application/PostServiceTest.java
Labels: 🔨 refactor

#134 [#133] Machine 초기 데이터 추가
  src/main/java/com/example/temp/machine/domain/MachineBodyPart.java
  src/main/resources/data.sql
Labels: ⚙ Setting

#127 [#122, #126] 운동 기록 수정, 삭제
  src/main/java/com/example/temp/common/exception/ErrorCode.java
  src/main/java/com/example/temp/record/application/ExerciseRecordService.java
  src/main/java/com/example/temp/record/domain/ExerciseRecord.java
  src/main/java/com/example/temp/record/dto/request/ExerciseRecordUpdateRequest.java
  src/main/java/com/example/temp/record/presentation/ExerciseRecordController.java
  src/test/java/com/example/temp/record/application/ExerciseRecordServiceTest.java
  src/test/java/com/example/temp/record/domain/ExerciseRecordTest.java
Labels: 💪🏻 feat

#132 [#123, #128] 사용자 정보 조회, 수정
  src/main/java/com/example/temp/member/application/MemberService.java
  src/main/java/com/example/temp/member/domain/Member.java
  src/main/java/com/example/temp/member/dto/request/MemberUpdateRequest.java
  src/main/java/com/example/temp/member/presentation/MemberController.java
  src/main/resources/data.sql
  src/test/java/com/example/temp/member/application/MemberServiceTest.java
Labels: 💪🏻 feat

#130 [#129] 게시글 생성 응답 형태 변경
  src/main/java/com/example/temp/post/application/PostService.java
  src/main/java/com/example/temp/post/dto/response/PostCreateResponse.java
  src/main/java/com/example/temp/post/presentation/PostController.java
  src/test/java/com/example/temp/post/application/PostServiceTest.java
Labels: 🔨 refactor

#137 [#121] 댓글 작성
  src/main/java/com/example/temp/comment/application/CommentService.java
  src/main/java/com/example/temp/comment/domain/Comment.java
  src/main/java/com/example/temp/comment/domain/CommentRepository.java
  src/main/java/com/example/temp/comment/domain/Content.java
  src/main/java/com/example/temp/comment/dto/request/CommentCreateRequest.java
  src/main/java/com/example/temp/comment/presentation/CommentController.java
  src/main/java/com/example/temp/common/exception/ErrorCode.java
  src/test/java/com/example/temp/comment/application/CommentServiceTest.java
  src/test/java/com/example/temp/comment/domain/CommentTest.java
Labels: 💪🏻 feat

#141 [#138] 댓글 조회 기능 추가
  src/main/java/com/example/temp/comment/application/CommentService.java
  src/main/java/com/example/temp/comment/domain/CommentRepository.java
  src/main/java/com/example/temp/comment/dto/response/CommentElementResponse.java
  src/main/java/com/example/temp/comment/dto/response/SliceCommentResponse.java
  src/main/java/com/example/temp/comment/presentation/CommentController.java
  src/test/java/com/example/temp/comment/application/CommentServiceTest.java
  src/test/java/com/example/temp/comment/domain/CommentRepositoryTest.java
Labels: 💪🏻 feat

#146 [#143] follows 테이블 초기 데이터 추가
  src/main/resources/data.sql
Labels: ⚙ Setting

#147 [#145] 게시글 조회 시 댓글 갯수 표시
  src/main/java/com/example/temp/comment/application/CommentService.java
  src/main/java/com/example/temp/post/domain/Post.java
  src/main/java/com/example/temp/post/dto/response/PostDetailResponse.java
  src/main/java/com/example/temp/post/dto/response/PostElementResponse.java
  src/test/java/com/example/temp/comment/application/CommentServiceTest.java
  src/test/java/com/example/temp/post/application/PostServiceTest.java
Labels: 💪🏻 feat

#151 [#148] 댓글 삭제
  src/main/java/com/example/temp/comment/application/CommentService.java
  src/main/java/com/example/temp/comment/domain/Comment.java
  src/main/java/com/example/temp/comment/domain/CommentRepository.java
  src/main/java/com/example/temp/comment/dto/response/CommentsResponse.java
  src/main/java/com/example/temp/comment/presentation/CommentController.java
  src/main/java/com/example/temp/common/exception/ErrorCode.java
  src/main/java/com/example/temp/post/domain/Post.java
  src/test/java/com/example/temp/comment/application/CommentServiceTest.java
  src/test/java/com/example/temp/comment/domain/CommentRepositoryTest.java
Labels: 💪🏻 feat

#160 [#150] 해시태그로 게시글 검색
  src/main/java/com/example/temp/comment/domain/CommentRepository.java
  src/main/java/com/example/temp/common/exception/ErrorCode.java
  src/main/java/com/example/temp/post/application/PostService.java
  src/main/java/com/example/temp/post/domain/PostHashtagRepository.java
  src/main/java/com/example/temp/post/domain/PostRepository.java
  src/main/java/com/example/temp/post/dto/response/PostSearchResponse.java
  src/main/java/com/example/temp/post/presentation/PostController.java
  src/test/java/com/example/temp/post/application/PostServiceTest.java
  src/test/java/com/example/temp/post/domain/PostRepositoryTest.java
Labels: 💪🏻 feat

#161 [#135] 운동기록 스냅샷
  src/main/java/com/example/temp/record/application/ExerciseRecordService.java
  src/main/java/com/example/temp/record/domain/ExerciseRecord.java
  src/main/java/com/example/temp/record/domain/ExerciseRecordRepository.java
  src/main/java/com/example/temp/record/domain/SetInTrack.java
  src/main/java/com/example/temp/record/domain/Track.java
  src/main/java/com/example/temp/record/dto/response/ExerciseRecordInfo.java
  src/main/java/com/example/temp/record/dto/response/RecordSnapshotsResponse.java
  src/main/java/com/example/temp/record/presentation/ExerciseRecordController.java
  src/test/java/com/example/temp/record/application/ExerciseRecordServiceTest.java
  src/test/java/com/example/temp/record/domain/ExerciseRecordRepositoryTest.java
  src/test/java/com/example/temp/record/domain/ExerciseRecordTest.java
  src/test/java/com/example/temp/record/domain/SetInTrackTest.java
  src/test/java/com/example/temp/record/domain/TrackTest.java
Labels: 💪🏻 feat

#164 [#163] access token을 사용해 자신의 정보를 가져오는 기능
  src/main/java/com/example/temp/member/presentation/MemberController.java
Labels: 💪🏻 feat

#167 [#166] refactor: findNextSnapshotsByMember메서드에 @Param 추가
  src/main/java/com/example/temp/record/domain/ExerciseRecordRepository.java
Labels: 🔨 refactor

#169 [#168] ExerciseRecordResponse 내부 구조 변경
  src/main/java/com/example/temp/record/application/ExerciseRecordService.java
  src/main/java/com/example/temp/record/dto/response/ExerciseRecordInfo.java
  src/main/java/com/example/temp/record/dto/response/ExerciseRecordResponse.java
  src/main/java/com/example/temp/record/dto/response/RecordSnapshotsResponse.java
  src/main/java/com/example/temp/record/dto/response/RetrievePeriodExerciseRecordsResponse.java
  src/main/java/com/example/temp/record/dto/response/RetrieveRecordSnapshotsResponse.java
  src/main/java/com/example/temp/record/dto/response/TrackInfoCategorizedBodyPart.java
  src/main/java/com/example/temp/record/presentation/ExerciseRecordController.java
  src/test/java/com/example/temp/record/application/ExerciseRecordServiceTest.java
Labels: 🔨 refactor

#171 [#170] 해시태그 검색 결과 리팩터링
  src/main/java/com/example/temp/post/application/PostService.java
  src/main/java/com/example/temp/post/domain/PostRepository.java
  src/main/java/com/example/temp/post/presentation/PostController.java
  src/test/java/com/example/temp/post/application/PostServiceTest.java
  src/test/java/com/example/temp/post/domain/PostRepositoryTest.java
Labels: 🔨 refactor

#173 [#172] 회원 삭제 시 연관된 게시물, 댓글이 삭제되지 않는 이슈
  src/main/java/com/example/temp/comment/application/CommentService.java
  src/main/java/com/example/temp/comment/domain/CommentRepository.java
  src/main/java/com/example/temp/post/application/PostService.java
  src/test/java/com/example/temp/comment/domain/CommentRepositoryTest.java
Labels: 🐞 BugFix
